-- Schema inicial do MVP Reviggo — Protocolo Corpo Revigorado
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text,
  household_size int default 1,
  cooking_time_preference int,
  cooking_skill text,
  primary_interest text,
  budget_priority text,
  subscription_status text default 'inactive',
  current_day int default 1,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists recipe_favorites (
  user_id uuid references profiles(id) on delete cascade,
  recipe_code text not null,
  created_at timestamptz default now(),
  primary key (user_id, recipe_code)
);

create table if not exists recipe_completions (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  recipe_code text not null,
  plan_day int,
  completed_at timestamptz default now()
);

create table if not exists daily_progress (
  user_id uuid references profiles(id) on delete cascade,
  plan_day int not null,
  completed boolean default false,
  completed_at timestamptz,
  primary key (user_id, plan_day)
);

create table if not exists tracker_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  entry_date date default current_date,
  energy int check (energy between 1 and 5),
  sleep int check (sleep between 1 and 5),
  meal_comfort int check (meal_comfort between 1 and 5),
  satiety int check (satiety between 1 and 5),
  note text,
  created_at timestamptz default now()
);

create table if not exists user_settings (
  user_id uuid primary key references profiles(id) on delete cascade,
  excluded_foods text[] default '{}',
  preferred_objectives text[] default '{}',
  notifications_enabled boolean default true,
  updated_at timestamptz default now()
);
